version: "3"
services:
  server:
    image: farahhachicha/orderimage
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://orderdb:3306/orderdb?useSSL=false
    networks:
      - ordernetwork
    depends_on:
      - orderdb

  orderdb:
    image: mysql:5.7
    networks:
      - ordernetwork
    environment:
      - MYSQL_ROOT_PASSWORD=Farah@99
      - MYSQL_DATABASE=orderdb


networks:
        ordernetwork:
